### ISSUE TITLE
EUCentralEUDCCTrustService not working anymore

### ISSUE THREAD

**Issue by ygini** [SvenTiigi/EUDCCKit#2]
Current URL for EUCentralEUDCCTrustService seems to be invalid.

It worked few days ago then starting to fail.

Decoding the current content at the check URL look like a testing content let here during penntest.

Do you have the update URL maybe?

**Comment by SvenTiigi** [comment]
Fixed with version [`0.0.2`](https://github.com/SvenTiigi/EUDCCKit/releases/tag/0.0.2)

**Comment by ygini** [comment]
Does it work for you? 

Here is the content I get from the new URL, and I cannot validate a certificate with it

```
curl https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateUpdate
MIICgDCCAiegAwIBAgIUSqpBK1Y/zs7XsVkhpdRpWjHVB8wwCgYIKoZIzj0EAwIwgYgxCzAJBgNVBAYTAkVFMREwDwYDVQQIDAhIYXJqdW1hYTEQMA4GA1UEBwwHVGFsbGlubjE2MDQGA1UECgwtSGVhbHRoIGFuZCBXZWxmYXJlIEluZm9ybWF0aW9uIFN5c3RlbXMgQ2VudGVyMRwwGgYDVQQDDBNER0NfQ1NDQV9URVNUX0VFXzAxMB4XDTIxMDUxODEzMjQ0NloXDTIyMDUxODEzMjQ0NlowgYoxCzAJBgNVBAYTAkVFMREwDwYDVQQIDAhIYXJqdW1hYTEQMA4GA1UEBwwHVGFsbGlubjE2MDQGA1UECgwtSGVhbHRoIGFuZCBXZWxmYXJlIEluZm9ybWF0aW9uIFN5c3RlbXMgQ2VudGVyMR4wHAYDVQQDDBVER0NfRFNDX0FQX1RFU1RfRUVfMDQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATVW/uZZUUBJalhWieIdI/qtqmCxZZKFPOznqfX5GoEGDRtgmx+SaOWxN3UmSfUrkhbOFH5pg23pIZL6LsjWJwNo2swaTAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFNjzMBphB6+qIfstZvk49nNUER+NMB8GA1UdIwQYMBaAFMIImDrw7d914Bq0qkriP5jvisICMBcGA1UdJQQQMA4GDCsGAQQBAI43j2UBAjAKBggqhkjOPQQDAgNHADBEAiBv956GRGl3/498+9PNO5KF1jDrFnezWiMb911738I6UgIgKJyM7SWzfc1rGnZnFqIgWUzVFm8Bz67mZ3OPSFC0zlw=%
```

**Comment by SvenTiigi** [comment]
The `signercertificateUpdate` endpoint from the dgca verifier service is built in a way that it needs to be called recursively.

When perfoming a request to the endpoint you retrieve the first certificate in the body of the HTTP response as well as the `KID` of the certificate in the HTTP response header `x-kid`. Secondly, you can access a resume token via the HTTP response header field `x-resume-token` to perform the next request until the endpoint doesn't responds a resume token back.

The `EUCentralEUDCCTrustService` implements this behaviour and fetches all certificates recursively.
See attached a screenshot of a  test which contains all 74 certificates.
![Screenshot](https://user-images.githubusercontent.com/11733014/127032174-d787ce14-21d9-4093-9bfa-d33354ddd6fc.png)

**Comment by SvenTiigi** [comment]
Of course it depends on the certificate you try to verify. Because the EU Digital COVID Certificate infrastructure hasn't got a single verifier service to retrieve all TrustCertificates it is rather an implementation each country needs to provide. For example a COVID certificate which was issued in Germany can be verified by using the verifier service from the Robert-Koch-Institute (`RobertKochInstituteEUDCCTrustService`)

So for another country like France a specific implementation has to be made to verify EU Digital COVID Certificates which has been issued in France.

**Comment by ygini** [comment]
OK. Interesting. For whatever reasons, the EU Central service does not have the FR one (`fGLuvg6n5wk=`) in the 74, but the german one have it…

And here in France the government don't share anything, we don't have any public API available to collect the public keys (or I didn't find it).
