### ISSUE TITLE
EUDCC Validator to test validity of a vaccination certificate of an EUDCC certification

### ISSUE THREAD

**Issue by pinelliantonio** [SvenTiigi/EUDCCKit#6]
## EUDCCKit Environment

- EUDCCKit version: 0.0.2
- macOS version: 11.4
- Xcode version: 12.5
- Dependency manager SPM

## What did you do?

 ℹ  EUDCC Validator to test validity of a vaccination certificate of an EUDCC certification

## What did you expect to happen?

ℹ The validator with default validation {
**_let defaultValidationRule: EUDCC.ValidationRule = .if(
    .isVaccination,
    then: .isFullyImmunized() && .isWellKnownVaccineMedicinalProduct && !.isVaccinationExpired(),
    else: .if(
        .isTest,
        then: .isTestedNegative && .isTestValid(),
        else: .if(
            .isRecovery,
            then: .isRecoveryValid,
            else: .constant(false)
        )
    )
)}_**
## What happened instead?
Fails validation of a vaccination certificate and returns at any case the failure value but if you removes the !(for testing the precedence of invoking operands) every time the predicate returns a succesfully operation, for clarirify the context of testing cases, will explains that the data used is taken from the official dgc test, used a 365 days expired vaccination certificate from belgium test and other in this repo. This problem is present only in the vaccination certificates, test and recovery works very well. Failure are related only with all predicate invoking date verification in vaccination certificates versions with default and passed by parameters invocation methods.
Thanks for the beautiful work, this is a very nice and perfect swift library. I was very nice to help improving of this library.

**Comment by SvenTiigi** [comment]
Hi @pinelliantonio 

Thanks for your bug report.

Just to clarify: Your currently expiring an issue with the `EUDCC.ValidiationRule.default` is that correct?

As the `EUDCCKit` is still in beta the `EUDCCValidation` target needs to be updated/refactored to use the official DGC JSON Rules API.

Therefore the `EUDCCValidation` is currently built with self-defined rules which might be not correct!
Please feel free to create your own `EUDCC.ValidationRule` or open up a PR.

**Comment by pinelliantonio** [comment]
Hi @SvenTiigi, thanks for the reply,
> Just to clarify: Your currently expiring an issue with the `EUDCC.ValidiationRule.default` is that correct?
Tested all methods, with static rules instantiated(let rule....), single methods call with default values and passed by parameters value [example **_isVaccinationExpired(),.isVaccinationExpired(maximumDaysSinceVaccinationDate: , using:)_**] with single if closure, problem affilcts only the versions of validator methods with dates comparators.

**Comment by pinelliantonio** [comment]
Sorry for the delay but I looked there is a bug in library, if you like I’d be able to explain that. The validator works flawlessly with this.

**Comment by SvenTiigi** [comment]
Closing this issue for now.
Please open up a PR which contains the fix for the aforementioned issue.
