### ISSUE TITLE
Fatal error: Not enough bits to represent the passed value

### ISSUE THREAD

**Issue by mousash** [SvenTiigi/EUDCCKit#7]
## EUDCCKit Environment

- EUDCCKit version: 0.0.2
- macOS version: 11.5.2
- Xcode version: 12.5.1
- Dependency manager (Carthage, CocoaPods, SPM, Manually): SPM

## What did you do?

Scanning recovery QR code

## What did you expect to happen?

Getting base 45 decode data from the given QR code

## What happened instead?

I got fatal error while decoding the base45 with the following message: Fatal error: Not enough bits to represent the passed value

<img width="1029" alt="Screenshot 2021-09-14 at 13 51 30" src="https://user-images.githubusercontent.com/45393448/133253497-53fa5f87-cb8b-4dec-b4a0-21cf70c606bb.png">

**Comment by SvenTiigi** [comment]
Hi @mousash 

Thanks for your bug report.

Would it be possible for you to share the Base-45 encoded String in order to investigate this error?

**Comment by mousash** [comment]
Hi @SvenTiigi 

Thanks for your reply, actually I got the QR Code from this [link](https://www.coronawarn.app/assets/img/blog/2021-07-12-cwa-2-5/certificate-of-recovery%20(1).png): and when I checked it more, it is  a fake code. but it would be nice if we could avoid fatal error in these cases when user scans a none related QR code.

base45EncodedString: "HTTPS://CORONAWARN.APP/E1/BIPEY33SMVWSA2LQON2W2IDEN5WG64RAONUXIIDBNVSXILBAMNXRBCM4UQARRKM6UQASAHRKCC7CTDWGQ4JCO7RVZSWVIMQK4UPA.GBCAEIA7TEORBTUA25QHBOCWT26BCA5PORBS2E4FFWMJ3UU3P6SXOL7SHUBCA7UEZBDDQ2R6VRJH7WBJKVF7GZYJA6YMRN27IPEP7NKGGJSWX3XQ"

**Comment by SvenTiigi** [comment]
Hi @mousash 

This problem has now been fixed with the latest release [`0.0.3`](https://github.com/SvenTiigi/EUDCCKit/releases/tag/0.0.3) of EUDCCKit
